configMapGenerator:
- files:
  - application.yml
  name: "82140964-configmap"
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ce82140964acr.azurecr.io/82140964
  newTag: "202411250816"
